### PR TITLE
homebrew 镜像帮助更新

### PR DESCRIPTION
**Pull request by silverbzez**
参考 tuna/mirror-web#377

两份文档差别有点大，所以仅更改了：
* 移除homebrew-cask-drivers仓库的支持
* 置顶所有有关brew版本更新引起的镜像变化的注解
* 分离<复原仓库上游>章节下Homebrew与Linuxbrew共用的codeblock

对于homebrew-services部分未进行更改，有这个需求可以再讨论

### CODE REVIEW

**Comment by ZenithalHourlyRate** [comment]
Should be made against https://github.com/mirrorz-org/mirrorz-help

**Comment by silverbzez** [comment]
> Should be made against https://github.com/mirrorz-org/mirrorz-help

so i should fork that repo and make changes over there instead of here right? 

still kinda confused, i should make changes based on that repo but where to create this pr? to here or to mirrorz-org/mirrorz-help?

**Comment by ZenithalHourlyRate** [comment]
> still kinda confused, i should make changes based on that repo but where to create this pr? to here or to mirrorz-org/mirrorz-help?

Make changes against mirrorz-org/mirrorz-help and create PR there; changes will be automatically synced here using github actions.

**Comment by silverbzez** [comment]
> Make changes against mirrorz-org/mirrorz-help and create PR there

That's much more clear, thx. This PR then will be closed.

**Pull request closed without merging**
